### ISSUE TITLE
mportError: cannot import name 'Markup' from 'jinja2'

### ISSUE THREAD

**Issue by dcasanovasos** [tanrax/flask-contacts#12]
I installed all the dependencies according to requirements.txt. Should it be updated with new Flask versions?

(venv) :~/flask-contacts/flask-contacts$ python3 migrations.py
Traceback (most recent call last):
  File "/home/mentor/flask-contacts/flask-contacts/migrations.py", line 1, in <module>
    from models import db, Contact
  File "/home/mentor/flask-contacts/flask-contacts/models.py", line 1, in <module>
    from flask import Flask
  File "/home/mentor/flask-contacts/venv/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/home/mentor/flask-contacts/venv/lib/python3.10/site-packages/jinja2/__init__.py)

**Comment by tanrax** [comment]
It seems that the import has been deprecated. The solution is given here. However, I will make a correction.
https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2

Thanks!

**Comment by dcasanovasos** [comment]
This is the requirements.txt that works for Python 3.10.6:

Faker==0.7.11
Flask==2.0.3
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
gunicorn
Werkzeug==2.0.3
Jinja2==3.0.0
email_validator

Thanks!

**Comment by tanrax** [comment]
I have updated the requirements.txt file
Thank you!
